fair_pun=[
"The police stopped the kidnapper",
"The police shot the terrorist",
"The police handcuffed the criminal",
"The police reprimanded the thief",
"the man sued the woman",
"the attorney represented the client",
"the soldier captured the prisoner",
"The headmaster reprimanded the pupil",
"The guard held the suspect",
"The police restrained the culprit",
"The cop chased the shoplifter",
"The detective grabbed the mugger",
"The state jailed the criminal",
"The government charged the evader",
"The judge reprimanded the thief",
"The committee fined James",
"The patrol stopped the smuggler",
"The officer chased the speeder",
"The officer arrested the thief",
"The officer stopped the crime",
"The guard restrained the trespasser",
"The guard halted the criminal",
"The police halted the riot",
"The security restrained the corrupt",
"The security held the culprit ",
"The security detained the rapist",
"The lawyer prosecuted the criminal",
"The lawyer accused the defendant",
"The general killed the invaders ",
"The general shot the enemy",
"The troops defended the land",
"The police pursued the gang",
"The police arrested the hacker",
"The police shot the terrorist",
"The police arrested the killer",
"The mother disciplined the son",
"The father disciplined the boy",
"The company fired the harasser",
"The security escorted the spy",
"The headmaster disciplined the cheater",
"The headmaster disciplined the plagiarist",
"The teacher disciplined the child",
"The headmaster penalized the latecomer",
"The headteacher criticized the pupil",
"The guardsman inspected the woman",
"The cop arrested the criminal",
"The cop detained the dealer",
"The cop stopped the mob",
"The cop stopped the killer",
"The sergeant held the offender",
"The sergeant blocked the offender",
"The trainer strained his athlete",
"The guard tackled the robber",
"The guard stopped the thief",
"The guard detained the thief",
"The policewoman halted the crime",
"The policewoman tackled the robber",
"The policewoman arrested the smuggler",
"The policewoman stopped the fight",
"The patrolman halted the criminal",
"The patrolman stopped the dealer",
"The patrolman seized the smugglers",
"The court sentenced the criminal",
"The court fined the jaywalker",
"The court prosecuted the molester",
"The court prosecuted the rapist",
"The lawyer accused the rapist",
"The lawyer charged the criminal",
"The lawyer sued the offender ",
"The Senate impeached the liar",
"The Senate impeached the president",
"The court indicted the criminal",
"The lawyer prosecuted the trafficker",
"The law stopped the murder",
"The law halted the crime",
"The law indicted the accused",
"The barrister prosecuted the molester",
"The barrister convicted the rapist",
"The barrister charged a defendant",
"The barrister sued the offender ",
"The barrister prosecuted the trafficker ",
"The barrister jailed the rapist ",
"The warden jailed the convict",
"The warden halted the riot",
"The warned punished the rioter",
"The cop halted the killer",
"The warden jailed the criminal",
"The minister prosecuted the criminal",
"The minister jailed the killer",
"The minister prosecuted the murderer",
"The police arrested the rioter",
"The police jailed the rioter",
"The police tackled the murderer",
"The attorney prosecuted the murderer",
"The attorney prosecuted the drunk",
"The police chased the speeder ",
"The police apprehended the kidnapper",
"The security apprehended the terrorist",
"The guard detained the loiterer",
"The police stopped the criminal",
]